version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest  # Updated to official ClickHouse image
    container_name: clickhouse-server
    ports:
      - "8123:8123"    # HTTP interface
      - "9000:9000"    # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default           # Removed - prefix for consistency
      CLICKHOUSE_USER: default         # Removed - prefix for consistency
      CLICKHOUSE_PASSWORD: ""          # Empty string instead of blank
    ulimits:                         # Added recommended ulimits for ClickHouse
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:                     # Added healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  clickhouse_data: