version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042" # CQL
      - "9160:9160" # Thrift
      - "10000:10000" # REST API
    volumes:
      - "${PWD}/scylla_data:/var/lib/scylla"
    environment:
      - SCYLLA_JMX_ADDR=-ja 0.0.0.0
      - SCYLLA_JMX_PORT=7199
    networks:
      - scylla_net
    restart: unless-stopped


volumes:
  scylla_data:
    name: scylla_data

networks:
  scylla_net:
    driver: bridge